Plane wrapping
webaverse/pistol-old pull request #1
Opened 2021-11-26 13:56 UTC by bru345

Decal system by buffer geometry position manipulation.

How to:
1. Pick up gun and fire at any mesh.
2. See decal appear

Known issues: 
1. Decal system, like DecalGeometry.js, has issues with certain meshes. Can appear inside some meshes, although it's fine on most.

Planned Optimisation: 
1. Moving Decal in its own repo.
2. Expose values (size, texture image, etc) so other systems can easily utilise it
3. Manage decals in scene either by Objectpool or use Three Instance mesh - https://threejs.org/docs/#api/en/objects/InstancedMesh 
4. Use promise instead of setTimeout.
5. z-fighting issues (could be fixed shader side)

Notes: 
You can change the decal image by placing a new jpg or png in the root folder and updating the variable 'decalTextureName' with the file name.

You can remove the green debug cubes by flipping the bool 'debugDecalVertPos' to false.

2021-11-27 10:34 UTC, avaer commented on index.js
> +            setTimeout(() => {
Why `setTimeout`?

2021-11-27 10:34 UTC, avaer commented on index.js
> +              if (planeGeo instanceof THREE.BufferGeometry)
Why would this be false?

2021-11-27 10:38 UTC, avaer requested changes
Some code questions, but the bigger issue is that this is creating a new untracked plane on each hit.

Imo the planes should all be accumulated into a draw range limited Geometry, with a single material. Then you can copy in a new PlaneBufferGeometry transformed with the correct matrix, pasted into the BufferGeometry, with the update range and draw range updated accordingly.

Futhermore, when we break this out in to a separate decal app, it should clean up after itself and not leave the meshes lying around. The `useCleanup` hook is for that.

2021-11-27 10:40 UTC, avaer commented
The reason for the above is performance; all of the decals can and should be a single draw call.

2021-11-27 10:40 UTC, avaer commented
https://threejs.org/docs/#api/en/core/BufferGeometry.drawRange

2021-11-27 10:42 UTC, avaer commented on index.js
> +            const modiPoint = newPointVec.add(new Vector3(0, normal.y /20 ,0));
This factor looks like it should be a constant to me.

2021-11-27 10:45 UTC, avaer commented
(the main issue is point 3 in the description)

> Manage decals in scene either by Objectpool or use Three Instance mesh - https://threejs.org/docs/#api/en/objects/InstancedMesh

Though I don't know if this will make sense with instanced mesh. All of the geos are actually unique, so there isn't much to instance.

2021-11-27 10:50 UTC, avaer commented
Also @skaljac is working on a way to do multiple raycasts in a single call. When that is done it is worth using here, again for performance.

2021-11-27 19:05 UTC, bru345 commented on index.js
> +              if (planeGeo instanceof THREE.BufferGeometry)
because of execution of order, sometimes planeGeo would be undefined.  It's redundant and should be removed.

2021-12-17 01:09 UTC, avaer commented
This looks ok for now, will merge and continue optimization work in pistol master.

2021-12-17 01:09 UTC, merged